#!/usr/bin/env bash
# Regenerate the human-readable schema snapshot from the live database.
# This file is REFERENCE ONLY -- migrations create the schema, never this.
set -euo pipefail
cd "$(dirname "$0")/.."
{
  echo "-- GENERATED by scripts/dump-schema.sh -- do not edit, do not execute."
  echo "-- Schema is created by Alembic migrations in alembic/versions/."
  echo "-- Regenerate with: make schema-dump"
  echo
  pg_dump -d "${SENTINEL_PG_DB:-sentinel}" --schema-only --no-owner --no-privileges
} > docs/schema.reference.sql
echo "docs/schema.reference.sql regenerated"
