-- GENERATED by scripts/dump-schema.sh -- do not edit, do not execute.
-- Schema is created by Alembic migrations in alembic/versions/.
-- Regenerate with: make schema-dump

--
-- PostgreSQL database dump
--

\restrict y5Nq4djPsJJPhx45TZyMR19bZmjWOeglEHVCZBhX1OD1g8e081Y6Xe2skf3qQgY

-- Dumped from database version 18.6 (Homebrew)
-- Dumped by pg_dump version 18.6 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: btree_gin; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS btree_gin WITH SCHEMA public;


--
-- Name: EXTENSION btree_gin; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION btree_gin IS 'support for indexing common datatypes in GIN';


--
-- Name: citext; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;


--
-- Name: EXTENSION citext; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION citext IS 'data type for case-insensitive character strings';


--
-- Name: pg_stat_statements; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_stat_statements WITH SCHEMA public;


--
-- Name: EXTENSION pg_stat_statements; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pg_stat_statements IS 'track planning and execution statistics of all SQL statements executed';


--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


--
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';


--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


--
-- Name: unaccent; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA public;


--
-- Name: EXTENSION unaccent; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION unaccent IS 'text search dictionary that removes accents';


--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


--
-- Name: prune_risk_history(integer); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.prune_risk_history(retain_days integer DEFAULT 90) RETURNS bigint
    LANGUAGE sql
    AS $$
            WITH pruned AS (
                UPDATE risk_assessments
                SET factors = '{}'::jsonb
                WHERE NOT is_current
                  AND computed_at < now() - make_interval(days => retain_days)
                  AND factors <> '{}'::jsonb
                RETURNING 1
            )
            SELECT count(*) FROM pruned;
        $$;


--
-- Name: FUNCTION prune_risk_history(retain_days integer); Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON FUNCTION public.prune_risk_history(retain_days integer) IS 'Drop the factors explanation from superseded assessments older than retain_days. Score, band and due_date are always kept.';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: alembic_version; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.alembic_version (
    version_num character varying(32) NOT NULL
);


--
-- Name: assets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assets (
    id bigint NOT NULL,
    hostname public.citext NOT NULL,
    ip_address inet,
    os_family text NOT NULL,
    os_version text,
    environment text NOT NULL,
    business_criticality smallint NOT NULL,
    internet_facing boolean DEFAULT false NOT NULL,
    data_classification text DEFAULT 'internal'::text NOT NULL,
    owner_team text NOT NULL,
    owner_email public.citext NOT NULL,
    tags jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT assets_business_criticality_check CHECK (((business_criticality >= 1) AND (business_criticality <= 5)))
);


--
-- Name: assets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.assets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: assets_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.assets_id_seq OWNED BY public.assets.id;


--
-- Name: corpus_chunks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.corpus_chunks (
    id bigint NOT NULL,
    document_id bigint NOT NULL,
    chunk_index integer NOT NULL,
    content text NOT NULL,
    cve_ids text[] DEFAULT '{}'::text[] NOT NULL,
    source text NOT NULL,
    os_family text,
    embedding public.vector(384),
    tsv tsvector GENERATED ALWAYS AS (to_tsvector('english'::regconfig, content)) STORED
);


--
-- Name: corpus_chunks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.corpus_chunks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: corpus_chunks_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.corpus_chunks_id_seq OWNED BY public.corpus_chunks.id;


--
-- Name: corpus_documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.corpus_documents (
    id bigint NOT NULL,
    source text NOT NULL,
    source_ref text NOT NULL,
    title text,
    cve_ids text[] DEFAULT '{}'::text[] NOT NULL,
    os_family text,
    raw_text text NOT NULL,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: corpus_documents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.corpus_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: corpus_documents_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.corpus_documents_id_seq OWNED BY public.corpus_documents.id;


--
-- Name: cves; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cves (
    cve_id text NOT NULL,
    published_at timestamp with time zone,
    last_modified_at timestamp with time zone,
    description text,
    cvss_v31_score numeric(3,1),
    cvss_v31_vector text,
    cvss_v40_score numeric(3,1),
    cvss_v40_vector text,
    cvss_severity text,
    cwe_ids text[] DEFAULT '{}'::text[] NOT NULL,
    reference_urls text[] DEFAULT '{}'::text[] NOT NULL,
    kev_listed boolean DEFAULT false NOT NULL,
    kev_date_added date,
    kev_due_date date,
    kev_ransomware boolean DEFAULT false NOT NULL,
    epss_score numeric(6,5),
    epss_percentile numeric(6,5),
    epss_updated_at timestamp with time zone,
    enriched_at timestamp with time zone
);


--
-- Name: findings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.findings (
    id bigint NOT NULL,
    asset_id bigint NOT NULL,
    cve_id text NOT NULL,
    package_name text NOT NULL,
    installed_version text NOT NULL,
    fixed_version text,
    package_type text,
    status text DEFAULT 'open'::text NOT NULL,
    first_seen timestamp with time zone DEFAULT now() NOT NULL,
    last_seen timestamp with time zone DEFAULT now() NOT NULL,
    resolved_at timestamp with time zone,
    first_scan_id bigint,
    last_scan_id bigint
);


--
-- Name: findings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.findings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: findings_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.findings_id_seq OWNED BY public.findings.id;


--
-- Name: remediation_plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.remediation_plans (
    id bigint NOT NULL,
    cve_id text NOT NULL,
    package_name text NOT NULL,
    os_family text NOT NULL,
    fixed_version text,
    plan_markdown text NOT NULL,
    commands jsonb DEFAULT '[]'::jsonb NOT NULL,
    rollback text,
    compensating_controls text,
    requires_reboot boolean,
    context_chunk_ids bigint[] DEFAULT '{}'::bigint[] NOT NULL,
    citations jsonb DEFAULT '[]'::jsonb NOT NULL,
    model text NOT NULL,
    grounding_passed boolean DEFAULT false NOT NULL,
    grounding_report jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: remediation_plans_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.remediation_plans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: remediation_plans_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.remediation_plans_id_seq OWNED BY public.remediation_plans.id;


--
-- Name: risk_assessments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.risk_assessments (
    id bigint NOT NULL,
    finding_id bigint NOT NULL,
    risk_score numeric(5,2) NOT NULL,
    risk_band text NOT NULL,
    sla_days integer NOT NULL,
    due_date date NOT NULL,
    factors jsonb NOT NULL,
    policy_version text NOT NULL,
    computed_at timestamp with time zone DEFAULT now() NOT NULL,
    is_current boolean DEFAULT true NOT NULL
);


--
-- Name: risk_assessments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.risk_assessments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: risk_assessments_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.risk_assessments_id_seq OWNED BY public.risk_assessments.id;


--
-- Name: scans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scans (
    id bigint NOT NULL,
    scanner text NOT NULL,
    scanner_version text,
    target text NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    finished_at timestamp with time zone,
    raw_path text
);


--
-- Name: scans_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.scans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: scans_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.scans_id_seq OWNED BY public.scans.id;


--
-- Name: ticket_findings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ticket_findings (
    ticket_id bigint NOT NULL,
    finding_id bigint NOT NULL
);


--
-- Name: tickets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tickets (
    id bigint NOT NULL,
    idempotency_key text NOT NULL,
    sink text NOT NULL,
    external_id text,
    external_url text,
    title text NOT NULL,
    body text NOT NULL,
    owner_team text NOT NULL,
    owner_email text NOT NULL,
    risk_band text NOT NULL,
    due_date date NOT NULL,
    state text DEFAULT 'pending'::text NOT NULL,
    plan_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: tickets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.tickets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: tickets_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.tickets_id_seq OWNED BY public.tickets.id;


--
-- Name: v_current_risk; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.v_current_risk AS
 SELECT f.id AS finding_id,
    f.status,
    f.package_name,
    f.installed_version,
    f.fixed_version,
    f.package_type,
    f.first_seen,
    a.id AS asset_id,
    a.hostname,
    a.environment,
    a.internet_facing,
    a.business_criticality,
    a.owner_team,
    a.owner_email,
    c.cve_id,
    c.cvss_v31_score,
    c.cvss_severity,
    c.epss_score,
    c.kev_listed,
    c.kev_ransomware,
    ra.risk_score,
    ra.risk_band,
    ra.sla_days,
    ra.due_date,
    ra.factors,
    ra.policy_version,
    ra.computed_at,
    (ra.due_date < CURRENT_DATE) AS overdue,
    (ra.due_date - CURRENT_DATE) AS days_remaining
   FROM (((public.risk_assessments ra
     JOIN public.findings f ON ((f.id = ra.finding_id)))
     JOIN public.assets a ON ((a.id = f.asset_id)))
     JOIN public.cves c ON ((c.cve_id = f.cve_id)))
  WHERE ra.is_current;


--
-- Name: assets id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assets ALTER COLUMN id SET DEFAULT nextval('public.assets_id_seq'::regclass);


--
-- Name: corpus_chunks id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.corpus_chunks ALTER COLUMN id SET DEFAULT nextval('public.corpus_chunks_id_seq'::regclass);


--
-- Name: corpus_documents id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.corpus_documents ALTER COLUMN id SET DEFAULT nextval('public.corpus_documents_id_seq'::regclass);


--
-- Name: findings id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.findings ALTER COLUMN id SET DEFAULT nextval('public.findings_id_seq'::regclass);


--
-- Name: remediation_plans id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.remediation_plans ALTER COLUMN id SET DEFAULT nextval('public.remediation_plans_id_seq'::regclass);


--
-- Name: risk_assessments id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.risk_assessments ALTER COLUMN id SET DEFAULT nextval('public.risk_assessments_id_seq'::regclass);


--
-- Name: scans id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scans ALTER COLUMN id SET DEFAULT nextval('public.scans_id_seq'::regclass);


--
-- Name: tickets id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets ALTER COLUMN id SET DEFAULT nextval('public.tickets_id_seq'::regclass);


--
-- Name: alembic_version alembic_version_pkc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alembic_version
    ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);


--
-- Name: assets assets_hostname_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT assets_hostname_key UNIQUE (hostname);


--
-- Name: assets assets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT assets_pkey PRIMARY KEY (id);


--
-- Name: corpus_chunks corpus_chunks_document_id_chunk_index_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.corpus_chunks
    ADD CONSTRAINT corpus_chunks_document_id_chunk_index_key UNIQUE (document_id, chunk_index);


--
-- Name: corpus_chunks corpus_chunks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.corpus_chunks
    ADD CONSTRAINT corpus_chunks_pkey PRIMARY KEY (id);


--
-- Name: corpus_documents corpus_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.corpus_documents
    ADD CONSTRAINT corpus_documents_pkey PRIMARY KEY (id);


--
-- Name: corpus_documents corpus_documents_source_source_ref_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.corpus_documents
    ADD CONSTRAINT corpus_documents_source_source_ref_key UNIQUE (source, source_ref);


--
-- Name: cves cves_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cves
    ADD CONSTRAINT cves_pkey PRIMARY KEY (cve_id);


--
-- Name: findings findings_asset_id_cve_id_package_name_installed_version_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.findings
    ADD CONSTRAINT findings_asset_id_cve_id_package_name_installed_version_key UNIQUE (asset_id, cve_id, package_name, installed_version);


--
-- Name: findings findings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.findings
    ADD CONSTRAINT findings_pkey PRIMARY KEY (id);


--
-- Name: remediation_plans remediation_plans_cve_id_package_name_os_family_fixed_versi_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.remediation_plans
    ADD CONSTRAINT remediation_plans_cve_id_package_name_os_family_fixed_versi_key UNIQUE (cve_id, package_name, os_family, fixed_version);


--
-- Name: remediation_plans remediation_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.remediation_plans
    ADD CONSTRAINT remediation_plans_pkey PRIMARY KEY (id);


--
-- Name: risk_assessments risk_assessments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.risk_assessments
    ADD CONSTRAINT risk_assessments_pkey PRIMARY KEY (id);


--
-- Name: scans scans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scans
    ADD CONSTRAINT scans_pkey PRIMARY KEY (id);


--
-- Name: ticket_findings ticket_findings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ticket_findings
    ADD CONSTRAINT ticket_findings_pkey PRIMARY KEY (ticket_id, finding_id);


--
-- Name: tickets tickets_idempotency_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_idempotency_key_key UNIQUE (idempotency_key);


--
-- Name: tickets tickets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_pkey PRIMARY KEY (id);


--
-- Name: idx_assets_exposure; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assets_exposure ON public.assets USING btree (internet_facing, environment);


--
-- Name: idx_assets_owner; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_assets_owner ON public.assets USING btree (owner_team, owner_email);


--
-- Name: idx_chunks_cves; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chunks_cves ON public.corpus_chunks USING gin (cve_ids);


--
-- Name: idx_chunks_embedding; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chunks_embedding ON public.corpus_chunks USING hnsw (embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64');


--
-- Name: idx_chunks_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chunks_trgm ON public.corpus_chunks USING gin (content public.gin_trgm_ops);


--
-- Name: idx_chunks_tsv; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chunks_tsv ON public.corpus_chunks USING gin (tsv);


--
-- Name: idx_corpus_docs_cves; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_corpus_docs_cves ON public.corpus_documents USING gin (cve_ids);


--
-- Name: idx_cves_epss; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cves_epss ON public.cves USING btree (epss_score DESC NULLS LAST);


--
-- Name: idx_cves_kev; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cves_kev ON public.cves USING btree (kev_listed) WHERE kev_listed;


--
-- Name: idx_findings_asset; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_findings_asset ON public.findings USING btree (asset_id, status);


--
-- Name: idx_findings_fixgroup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_findings_fixgroup ON public.findings USING btree (asset_id, package_name, fixed_version) WHERE (status = 'open'::text);


--
-- Name: idx_findings_open; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_findings_open ON public.findings USING btree (status, cve_id) WHERE (status = 'open'::text);


--
-- Name: idx_risk_current_band; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_risk_current_band ON public.risk_assessments USING btree (risk_band, risk_score DESC) WHERE is_current;


--
-- Name: idx_risk_current_due; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_risk_current_due ON public.risk_assessments USING btree (due_date) WHERE is_current;


--
-- Name: idx_risk_due; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_risk_due ON public.risk_assessments USING btree (due_date, risk_band);


--
-- Name: idx_risk_finding; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_risk_finding ON public.risk_assessments USING btree (finding_id, computed_at DESC);


--
-- Name: uq_risk_current; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_risk_current ON public.risk_assessments USING btree (finding_id) WHERE is_current;


--
-- Name: corpus_chunks corpus_chunks_document_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.corpus_chunks
    ADD CONSTRAINT corpus_chunks_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.corpus_documents(id) ON DELETE CASCADE;


--
-- Name: findings findings_asset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.findings
    ADD CONSTRAINT findings_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.assets(id) ON DELETE CASCADE;


--
-- Name: findings findings_cve_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.findings
    ADD CONSTRAINT findings_cve_id_fkey FOREIGN KEY (cve_id) REFERENCES public.cves(cve_id) ON DELETE CASCADE;


--
-- Name: findings findings_first_scan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.findings
    ADD CONSTRAINT findings_first_scan_id_fkey FOREIGN KEY (first_scan_id) REFERENCES public.scans(id);


--
-- Name: findings findings_last_scan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.findings
    ADD CONSTRAINT findings_last_scan_id_fkey FOREIGN KEY (last_scan_id) REFERENCES public.scans(id);


--
-- Name: remediation_plans remediation_plans_cve_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.remediation_plans
    ADD CONSTRAINT remediation_plans_cve_id_fkey FOREIGN KEY (cve_id) REFERENCES public.cves(cve_id) ON DELETE CASCADE;


--
-- Name: risk_assessments risk_assessments_finding_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.risk_assessments
    ADD CONSTRAINT risk_assessments_finding_id_fkey FOREIGN KEY (finding_id) REFERENCES public.findings(id) ON DELETE CASCADE;


--
-- Name: ticket_findings ticket_findings_finding_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ticket_findings
    ADD CONSTRAINT ticket_findings_finding_id_fkey FOREIGN KEY (finding_id) REFERENCES public.findings(id) ON DELETE CASCADE;


--
-- Name: ticket_findings ticket_findings_ticket_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ticket_findings
    ADD CONSTRAINT ticket_findings_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.tickets(id) ON DELETE CASCADE;


--
-- Name: tickets tickets_plan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.remediation_plans(id);


--
-- PostgreSQL database dump complete
--

\unrestrict y5Nq4djPsJJPhx45TZyMR19bZmjWOeglEHVCZBhX1OD1g8e081Y6Xe2skf3qQgY

